services:
  - type: web
    name: stunting-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: MODEL_PATH
        value: model/final_model.pth
    autoDeploy: true